 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/masjids", type: :request do
  
  # Masjid. As you add validations to Masjid, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Masjid.create! valid_attributes
      get masjids_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      masjid = Masjid.create! valid_attributes
      get masjid_url(masjid)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_masjid_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      masjid = Masjid.create! valid_attributes
      get edit_masjid_url(masjid)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Masjid" do
        expect {
          post masjids_url, params: { masjid: valid_attributes }
        }.to change(Masjid, :count).by(1)
      end

      it "redirects to the created masjid" do
        post masjids_url, params: { masjid: valid_attributes }
        expect(response).to redirect_to(masjid_url(Masjid.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Masjid" do
        expect {
          post masjids_url, params: { masjid: invalid_attributes }
        }.to change(Masjid, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post masjids_url, params: { masjid: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested masjid" do
        masjid = Masjid.create! valid_attributes
        patch masjid_url(masjid), params: { masjid: new_attributes }
        masjid.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the masjid" do
        masjid = Masjid.create! valid_attributes
        patch masjid_url(masjid), params: { masjid: new_attributes }
        masjid.reload
        expect(response).to redirect_to(masjid_url(masjid))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        masjid = Masjid.create! valid_attributes
        patch masjid_url(masjid), params: { masjid: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested masjid" do
      masjid = Masjid.create! valid_attributes
      expect {
        delete masjid_url(masjid)
      }.to change(Masjid, :count).by(-1)
    end

    it "redirects to the masjids list" do
      masjid = Masjid.create! valid_attributes
      delete masjid_url(masjid)
      expect(response).to redirect_to(masjids_url)
    end
  end
end
