 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/packs", type: :request do
  
  # Pack. As you add validations to Pack, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Pack.create! valid_attributes
      get packs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pack = Pack.create! valid_attributes
      get pack_url(pack)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pack_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      pack = Pack.create! valid_attributes
      get edit_pack_url(pack)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Pack" do
        expect {
          post packs_url, params: { pack: valid_attributes }
        }.to change(Pack, :count).by(1)
      end

      it "redirects to the created pack" do
        post packs_url, params: { pack: valid_attributes }
        expect(response).to redirect_to(pack_url(Pack.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Pack" do
        expect {
          post packs_url, params: { pack: invalid_attributes }
        }.to change(Pack, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post packs_url, params: { pack: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pack" do
        pack = Pack.create! valid_attributes
        patch pack_url(pack), params: { pack: new_attributes }
        pack.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pack" do
        pack = Pack.create! valid_attributes
        patch pack_url(pack), params: { pack: new_attributes }
        pack.reload
        expect(response).to redirect_to(pack_url(pack))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pack = Pack.create! valid_attributes
        patch pack_url(pack), params: { pack: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pack" do
      pack = Pack.create! valid_attributes
      expect {
        delete pack_url(pack)
      }.to change(Pack, :count).by(-1)
    end

    it "redirects to the packs list" do
      pack = Pack.create! valid_attributes
      delete pack_url(pack)
      expect(response).to redirect_to(packs_url)
    end
  end
end
